### ISSUE TITLE
QASM is incompatible with Braket API

### ISSUE THREAD

**Issue by sw1sh** [qiskit-community/qiskit-braket-provider#81]
### Steps to reproduce the problem

```
from qiskit_braket_provider import AWSBraketProvider
from qiskit import QuantumCircuit, transpile

circuit = QuantumCircuit(2)

circuit.cx(0, 1)
circuit.measure([0, 1], [0, 1])

provider = AWSBraketProvider()
backend = provider.get_backend('SV1')

transpiled_circuit = transpile(circuit, backend=backend)
transpiled_circuit.qasm()
```

### What is the current behavior?

> OPENQASM 2.0;
> include "qelib1.inc";
> qreg q[34];
> creg c[2];
> cx q[0],q[1];
> measure q[0] -> c[0];
> measure q[1] -> c[1];

### What is the expected behavior?

There are a few issues:
- API complains about the include line 'include "qelib1.inc";', so it has to be removed
- it generates empty ancillas for some reason, which API also doesn't like
- 'cx' gate should be renamed to 'cnot', because this is the one supported by all AWS devices:
```
from braket.devices import LocalSimulator
LocalSimulator(backend='braket_sv').properties.action['braket.ir.openqasm.program'].supportedOperations
```

> [U,GPhase,ccnot,cnot,cphaseshift,cphaseshift00,cphaseshift01,cphaseshift10,cswap,cv,cy,cz,ecr,gpi,gpi2,h,i,iswap,ms,pswap,phaseshift,rx,ry,rz,s,si,swap,t,ti,unitary,v,vi,x,xx,xy,y,yy,z,zz]

**Comment by sw1sh** [comment]
I know one can convert to Braket circuit and use their qasm generator:
```
from qiskit_braket_provider.providers.adapter import convert_qiskit_to_braket_circuit
from braket.circuits.serialization import IRType
convert_qiskit_to_braket_circuit(circuit).to_ir(IRType.OPENQASM).source
```
But it would be nice to overload Qiskit's qasm() to use it for consistency.

**Comment by christianbmadsen** [comment]
@sw1sh Thank you for opening this issue!

It's great that you found the solution to convert to Braket circuit and the associated to_ir() method. Could you share more about your use case?

Braket circuits generally default to OpeQASM3.0 (see detail [here](https://docs.aws.amazon.com/braket/latest/developerguide/braket-openqasm.html)) where as Qiskit's qasm() returns OpenQASM2.0. Since Braket devices will not be able to consume the old version of the IR a translation has to happen somewhere - either translate OpenQASM2.0 to OpenQASM3.0 or translate a Qiskit circuit to a Braket circuit (which in turn gets turned into OpenQASM3.0).
